<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJvbijfp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJvbijfp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJvbijfp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJvbijfp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJvbijfp\appDevDebugProjectContainer([
    'container.build_hash' => 'Jvbijfp',
    'container.build_id' => '3bd17c51',
    'container.build_time' => 1667404382,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJvbijfp');
